language: android
env:
  global:
    # install timeout in minutes (2 minutes by default)
    - ADB_INSTALL_TIMEOUT=8
    - ANDROID_TARGET=android-22
android:
  components:
    - tools
    - platform-tools
    - build-tools-29.0.2
    - android-29
    - extra
    - $ANDROID_TARGET

  licenses:
    - 'android-sdk-preview-license-52d11cd2'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

# Run assemble and unit tests
script:
  - chmod +x ./gradlew
  - ./gradlew clean assembleDebug
  - ./gradlew clean assembleRelease
  - ./gradlew clean testDebug

before_install:
  - chmod +x gradlew

